######################################################################
# Automatically generated by qmake (3.0) Mon Jul 13 02:08:50 2015
######################################################################
QT += widgets

TEMPLATE = app
TARGET = DX12Frame
INCLUDEPATH += .

# Input
HEADERS += DX12RenderWidget.h DXGfxCore.h GFXBackEndThread.h
SOURCES += DX12RenderWidget.cpp DXGfxCore.cpp GFXBackEndThread.cpp main.cpp
